# Generated by Django 6.0.3 on 2026-03-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('capacidade_litros', models.PositiveIntegerField()),
                ('nivel_atual_litros', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('manutencao', 'Manutencao'), ('inativo', 'Inativo')], default='ativo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
