# Generated by Django 6.0.3 on 2026-03-23 12:24

from django.db import migrations, models


def migrar_status_antigo_para_novo(apps, schema_editor):
    Reservatorio = apps.get_model("app", "Reservatorio")
    mapa = {
        "ativo": "bom",
        "manutencao": "atencao",
        "inativo": "perigo",
    }
    for antigo, novo in mapa.items():
        Reservatorio.objects.filter(status=antigo).update(status=novo)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservatorio',
            name='capacidade_litros',
        ),
        migrations.RemoveField(
            model_name='reservatorio',
            name='nivel_atual_litros',
        ),
        migrations.RunPython(
            migrar_status_antigo_para_novo,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='reservatorio',
            name='status',
            field=models.CharField(choices=[('bom', 'Bom'), ('atencao', 'Atencao'), ('perigo', 'Perigo')], default='bom', max_length=20),
        ),
    ]
