# Generated by Django 6.0.3 on 2026-03-23 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def corrigir_chaves_estrangeiras_invalidas(apps, schema_editor):
    app_label, model_name = settings.AUTH_USER_MODEL.split(".")
    Usuario = apps.get_model(app_label, model_name)
    Reservatorio = apps.get_model("app", "Reservatorio")
    TDS = apps.get_model("app", "TDS")

    usuarios_validos = list(Usuario.objects.values_list("id", flat=True))
    if usuarios_validos:
        fallback_usuario_id = min(usuarios_validos)
        Reservatorio.objects.exclude(usuario_id__in=usuarios_validos).update(
            usuario_id=fallback_usuario_id
        )
    else:
        Reservatorio.objects.all().delete()

    reservatorios_validos = list(Reservatorio.objects.values_list("id", flat=True))
    if reservatorios_validos:
        fallback_reservatorio_id = min(reservatorios_validos)
        TDS.objects.exclude(reservatorio_id__in=reservatorios_validos).update(
            reservatorio_id=fallback_reservatorio_id
        )
    else:
        TDS.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_reservatorio_usuario_tds'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tds',
            options={'ordering': ['-data_hora']},
        ),
        migrations.RunPython(
            corrigir_chaves_estrangeiras_invalidas,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='reservatorio',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservatorios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tds',
            name='reservatorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicoes_tds', to='app.reservatorio'),
        ),
    ]
