# Generated by Django 6.0.3 on 2026-03-23 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_tds_options_alter_reservatorio_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temperatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celcius', models.IntegerField()),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('reservatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicoes_temperatura', to='app.reservatorio')),
            ],
            options={
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='Turbidez',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntu', models.IntegerField()),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('reservatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicoes_turbidez', to='app.reservatorio')),
            ],
            options={
                'ordering': ['-data_hora'],
            },
        ),
    ]
