# Generated by Django 6.0.3 on 2026-03-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_temperatura_turbidez'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tds',
            name='ppm',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='temperatura',
            name='celcius',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='turbidez',
            name='ntu',
            field=models.FloatField(),
        ),
    ]
