# Generated by Django 6.0.3 on 2026-03-23 14:45

import django.db.models.deletion
from django.db import migrations, models


def criar_pontos_monitoramento_padrao(apps, schema_editor):
    Reservatorio = apps.get_model("app", "Reservatorio")
    PontoMonitoramento = apps.get_model("app", "PontoMonitoramento")

    for reservatorio in Reservatorio.objects.all().iterator():
        PontoMonitoramento.objects.get_or_create(
            reservatorio_id=reservatorio.id,
            tipo="antes_tratamento",
        )
        PontoMonitoramento.objects.get_or_create(
            reservatorio_id=reservatorio.id,
            tipo="depois_tratamento",
        )


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_tds_ppm_alter_temperatura_celcius_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PontoMonitoramento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('antes_tratamento', 'Antes do tratamento'), ('depois_tratamento', 'Depois do tratamento')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reservatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontos_monitoramento', to='app.reservatorio')),
            ],
            options={
                'ordering': ['reservatorio_id', 'tipo'],
            },
        ),
        migrations.CreateModel(
            name='LeituraQualidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tds', models.FloatField()),
                ('temperatura', models.FloatField()),
                ('turbidez', models.FloatField()),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('ponto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras_qualidade', to='app.pontomonitoramento')),
            ],
            options={
                'ordering': ['-data_hora'],
            },
        ),
        migrations.RunPython(
            criar_pontos_monitoramento_padrao,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='pontomonitoramento',
            constraint=models.UniqueConstraint(fields=('reservatorio', 'tipo'), name='uq_ponto_monitoramento_reservatorio_tipo'),
        ),
        migrations.AddIndex(
            model_name='leituraqualidade',
            index=models.Index(fields=['ponto', 'data_hora'], name='app_leitura_ponto_i_8c5556_idx'),
        ),
    ]
