# Generated by Django 6.0.3 on 2026-03-23 15:09

from django.db import migrations, models


def _calcular_status(temperatura, tds, turbidez):
    if tds >= 900 or turbidez >= 2.5:
        return "perigo"
    if tds >= 600 or turbidez >= 1.5:
        return "atencao"
    return "bom"


def popular_statuses(apps, schema_editor):
    LeituraQualidade = apps.get_model("app", "LeituraQualidade")
    PontoMonitoramento = apps.get_model("app", "PontoMonitoramento")
    Reservatorio = apps.get_model("app", "Reservatorio")

    for leitura in LeituraQualidade.objects.all().iterator():
        leitura.status_ponto = _calcular_status(
            leitura.temperatura,
            leitura.tds,
            leitura.turbidez,
        )
        leitura.status_origem = "regras"
        leitura.save(update_fields=["status_ponto", "status_origem"])

    prioridade = {"bom": 0, "atencao": 1, "perigo": 2}

    for ponto in PontoMonitoramento.objects.all().iterator():
        ultima = (
            LeituraQualidade.objects.filter(ponto_id=ponto.id)
            .order_by("-data_hora", "-id")
            .first()
        )
        if ultima is None:
            ponto.status_atual = "bom"
        else:
            ponto.status_atual = ultima.status_ponto
        ponto.save(update_fields=["status_atual", "updated_at"])

    for reservatorio in Reservatorio.objects.all().iterator():
        statuses = list(
            PontoMonitoramento.objects.filter(reservatorio_id=reservatorio.id).values_list(
                "status_atual",
                flat=True,
            )
        )
        if not statuses:
            reservatorio.status = "bom"
        else:
            reservatorio.status = max(statuses, key=lambda status: prioridade.get(status, -1))
        reservatorio.save(update_fields=["status", "updated_at"])


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_pontomonitoramento_leituraqualidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leituraqualidade',
            name='confianca',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leituraqualidade',
            name='modelo_versao',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='leituraqualidade',
            name='status_origem',
            field=models.CharField(choices=[('regras', 'Regras'), ('tinyml', 'TinyML')], default='regras', max_length=16),
        ),
        migrations.AddField(
            model_name='leituraqualidade',
            name='status_ponto',
            field=models.CharField(choices=[('bom', 'Bom'), ('atencao', 'Atencao'), ('perigo', 'Perigo')], default='bom', max_length=20),
        ),
        migrations.AddField(
            model_name='pontomonitoramento',
            name='confianca_status',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pontomonitoramento',
            name='modelo_versao',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='pontomonitoramento',
            name='status_atual',
            field=models.CharField(choices=[('bom', 'Bom'), ('atencao', 'Atencao'), ('perigo', 'Perigo')], default='bom', max_length=20),
        ),
        migrations.AddField(
            model_name='pontomonitoramento',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RunPython(
            popular_statuses,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
