# Generated by Django 6.0.3 on 2026-03-23 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_leituraqualidade_confianca_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temperatura',
            name='reservatorio',
        ),
        migrations.RemoveField(
            model_name='turbidez',
            name='reservatorio',
        ),
        migrations.DeleteModel(
            name='TDS',
        ),
        migrations.DeleteModel(
            name='Temperatura',
        ),
        migrations.DeleteModel(
            name='Turbidez',
        ),
    ]
