# Generated by Django 6.0.3 on 2026-03-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_status_ponto_status_leitura'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservatorio',
            name='meta_celsius_temperatura',
            field=models.FloatField(default=25.0),
        ),
        migrations.AddField(
            model_name='reservatorio',
            name='meta_ntu_turbidez',
            field=models.FloatField(default=1.5),
        ),
        migrations.AddField(
            model_name='reservatorio',
            name='meta_ppm_tds',
            field=models.FloatField(default=600.0),
        ),
    ]
