# Generated by Django 6.0.3 on 2026-03-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_reservatorio_meta_celsius_temperatura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leituraqualidade',
            name='sinais_brutos',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
