# Generated by Django 6.0.3 on 2026-03-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_leituraqualidade_sinais_brutos'),
    ]

    operations = [
        migrations.AddField(
            model_name='leituraqualidade',
            name='ph',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservatorio',
            name='meta_ph',
            field=models.FloatField(default=7.0),
        ),
    ]
