# Generated by Django 6.0.3 on 2026-03-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_leituraqualidade_ph_reservatorio_meta_ph"),
    ]

    operations = [
        migrations.AddField(
            model_name="pontomonitoramento",
            name="ph_inclinacao",
            field=models.FloatField(default=0.23),
        ),
        migrations.AddField(
            model_name="pontomonitoramento",
            name="ph_voltagem_referencia_7",
            field=models.FloatField(default=2.39),
        ),
    ]
