# Generated by Django 6.0.3 on 2026-03-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_pontomonitoramento_calibracao_ph"),
    ]

    operations = [
        migrations.AddField(
            model_name="pontomonitoramento",
            name="ph_calibrado_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
