# Generated by Django 6.0.3 on 2026-03-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_pontomonitoramento_ph_calibrado_em"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservatorio",
            name="faixa_celsius_temperatura_max",
            field=models.FloatField(default=30.0),
        ),
        migrations.AddField(
            model_name="reservatorio",
            name="faixa_celsius_temperatura_min",
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name="reservatorio",
            name="faixa_ntu_turbidez_max",
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name="reservatorio",
            name="faixa_ntu_turbidez_min",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="reservatorio",
            name="faixa_ph_max",
            field=models.FloatField(default=9.5),
        ),
        migrations.AddField(
            model_name="reservatorio",
            name="faixa_ph_min",
            field=models.FloatField(default=6.0),
        ),
        migrations.AddField(
            model_name="reservatorio",
            name="faixa_ppm_tds_max",
            field=models.FloatField(default=500.0),
        ),
        migrations.AddField(
            model_name="reservatorio",
            name="faixa_ppm_tds_min",
            field=models.FloatField(default=0.0),
        ),
    ]
