# Generated by Django 6.0.3 on 2026-03-25 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_reservatorio_faixas_potabilidade"),
    ]

    operations = [
        migrations.AddField(
            model_name="pontomonitoramento",
            name="agua_calibrado_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pontomonitoramento",
            name="tds_adc_calibracao",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pontomonitoramento",
            name="tds_alvo_calibracao_ppm",
            field=models.FloatField(default=40.0),
        ),
        migrations.AddField(
            model_name="pontomonitoramento",
            name="tds_offset_ppm",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="pontomonitoramento",
            name="turbidez_adc_calibracao",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pontomonitoramento",
            name="turbidez_alvo_calibracao_ntu",
            field=models.FloatField(default=0.4),
        ),
        migrations.AddField(
            model_name="pontomonitoramento",
            name="turbidez_offset_ntu",
            field=models.FloatField(default=0.0),
        ),
    ]
