# Generated by Django 6.0.3 on 2026-04-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_pontomonitoramento_calibracao_agua"),
    ]

    operations = [
        migrations.AddField(
            model_name="pontomonitoramento",
            name="ph_temperatura_calibracao_c",
            field=models.FloatField(default=25.0),
        ),
        migrations.AddField(
            model_name="pontomonitoramento",
            name="temperatura_bruta_referencia_c",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pontomonitoramento",
            name="temperatura_calibrado_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pontomonitoramento",
            name="temperatura_inclinacao",
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name="pontomonitoramento",
            name="temperatura_offset_c",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="pontomonitoramento",
            name="temperatura_valor_referencia_c",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
