# Generated by Django 6.0.3 on 2026-04-06 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0018_pontomonitoramento_calibracao_temperatura"),
    ]

    operations = [
        migrations.AddField(
            model_name="pontomonitoramento",
            name="tds_calibrado_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pontomonitoramento",
            name="tds_inclinacao",
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name="pontomonitoramento",
            name="turbidez_calibrado_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pontomonitoramento",
            name="turbidez_inclinacao",
            field=models.FloatField(default=1.0),
        ),
    ]
