# Generated by Django 6.0.3 on 2026-04-06 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_pontomonitoramento_calibracao_tds_turbidez_independente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessaoCalibracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.CharField(choices=[('temperatura', 'Temperatura'), ('tds', 'TDS'), ('turbidez', 'Turbidez'), ('ph', 'pH')], max_length=20)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('encerrada', 'Encerrada'), ('expirada', 'Expirada')], default='ativa', max_length=16)),
                ('intervalo_envio_ms', models.PositiveIntegerField(default=5000)),
                ('qtd_amostras', models.PositiveIntegerField(default=80)),
                ('atraso_amostra_ms', models.PositiveIntegerField(default=50)),
                ('iniciada_em', models.DateTimeField(auto_now_add=True)),
                ('ultima_amostra_em', models.DateTimeField(blank=True, null=True)),
                ('encerrada_em', models.DateTimeField(blank=True, null=True)),
                ('expira_em', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('iniciada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessoes_calibracao_iniciadas', to=settings.AUTH_USER_MODEL)),
                ('ponto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes_calibracao', to='app.pontomonitoramento')),
            ],
            options={
                'ordering': ['-iniciada_em'],
            },
        ),
        migrations.CreateModel(
            name='AmostraCalibracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.FloatField(blank=True, null=True)),
                ('adc_tds', models.IntegerField(blank=True, null=True)),
                ('adc_turb', models.IntegerField(blank=True, null=True)),
                ('adc_ph', models.IntegerField(blank=True, null=True)),
                ('firmware_ts_ms', models.BigIntegerField(blank=True, null=True)),
                ('sinais_brutos', models.JSONField(blank=True, default=dict)),
                ('coletada_em', models.DateTimeField(auto_now_add=True)),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amostras', to='app.sessaocalibracao')),
            ],
            options={
                'ordering': ['-coletada_em'],
            },
        ),
        migrations.AddIndex(
            model_name='sessaocalibracao',
            index=models.Index(fields=['ponto', 'status', 'expira_em'], name='app_sessaoc_ponto_i_1c1857_idx'),
        ),
        migrations.AddIndex(
            model_name='sessaocalibracao',
            index=models.Index(fields=['ponto', 'sensor', 'status'], name='app_sessaoc_ponto_i_9aebad_idx'),
        ),
        migrations.AddIndex(
            model_name='amostracalibracao',
            index=models.Index(fields=['sessao', 'coletada_em'], name='app_amostra_sessao__e060df_idx'),
        ),
    ]
