# Generated by Django 6.0.3 on 2026-04-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_sessaocalibracao_amostracalibracao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessaocalibracao',
            name='dados_fluxo',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
