# Generated by Django 6.0.3 on 2026-06-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_reservatorio_esp32_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leituraqualidade',
            name='status_leitura',
            field=models.CharField(choices=[('bom', 'Bom'), ('atencao', 'Ateno'), ('perigo', 'Perigo')], default='bom', max_length=20),
        ),
        migrations.AlterField(
            model_name='pontomonitoramento',
            name='status_atual',
            field=models.CharField(choices=[('bom', 'Bom'), ('atencao', 'Ateno'), ('perigo', 'Perigo')], default='bom', max_length=20),
        ),
        migrations.AlterField(
            model_name='pontomonitoramento',
            name='tipo',
            field=models.CharField(choices=[('ponto_unico', 'Ponto único')], max_length=32),
        ),
        migrations.AlterField(
            model_name='reservatorio',
            name='status',
            field=models.CharField(choices=[('bom', 'Bom'), ('atencao', 'Ateno'), ('perigo', 'Perigo')], default='bom', max_length=20),
        ),
    ]
