# Generated by Django 6.0.3 on 2026-06-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0025_alter_leituraqualidade_status_leitura_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservatorio",
            name="alerta_sonoro_silenciado",
            field=models.BooleanField(default=False),
        ),
    ]
