# Generated by Django 6.0.3 on 2026-06-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0027_reservatorio_alerta_sonoro_silenciado_permanente"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservatorio",
            name="alerta_sonoro_teste_ate",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
