# Generated by Django 6.0.3 on 2026-06-22 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_reservatorio_alerta_sonoro_teste_ate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservatorio',
            name='esp32_token_integracao',
        ),
    ]
