# Generated by Django 6.0.3 on 2026-06-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_remove_reservatorio_esp32_token_integracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leituraqualidade',
            name='status_leitura',
            field=models.CharField(choices=[('bom', 'Bom'), ('atencao', 'Atenção'), ('perigo', 'Perigo')], default='bom', max_length=20),
        ),
        migrations.AlterField(
            model_name='pontomonitoramento',
            name='status_atual',
            field=models.CharField(choices=[('bom', 'Bom'), ('atencao', 'Atenção'), ('perigo', 'Perigo')], default='bom', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservatorio',
            name='status',
            field=models.CharField(choices=[('bom', 'Bom'), ('atencao', 'Atenção'), ('perigo', 'Perigo')], default='bom', max_length=20),
        ),
    ]
