# Generated by Django 6.0.3 on 2026-06-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_leituraqualidade_status_leitura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontomonitoramento',
            name='ph_solucao_calibracao_ponto_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pontomonitoramento',
            name='ph_solucao_calibracao_ponto_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pontomonitoramento',
            name='ph_tensao_calibracao_ponto_1_v',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pontomonitoramento',
            name='ph_tensao_calibracao_ponto_2_v',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pontomonitoramento',
            name='turbidez_referencia_calibracao_ponto_2_ntu',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pontomonitoramento',
            name='turbidez_tensao_calibracao_ponto_1_v',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pontomonitoramento',
            name='turbidez_tensao_calibracao_ponto_2_v',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
